spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@eventscluster.ucrgvqt.mongodb.net/${DB_NAME:webflux-db}?retryWrites=true&w=majority&appName=EventsCluster
      auto-index-creation: true
  application:
    name: webflux